#organization: abaltatech
#
#teams:
#  devops: 1
#  test-aproval: 1
#
#users:
#  - imarinov3
#  - valentinvarbanov

organization: actions-test-123

teams:
  grp1: 1
  grp2: 1

users:
  - imarinov3
  - valentinvarbanov
