name: approvals
on: 
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check Approvals
        id: check-approvals
        run: |
          res=$(python approvals.py approvals_config.yaml)

          status='pending'
        
          if [ "${res}" = '0' ]; then
            stauts='success'
          fi

          echo "Status: $status"
          payload='{
            "name": '"'approvals'"',
            "head_sha": '"'$(git rev-parse HEAD)'"',
            "status": '"'${status}'"'
          }'
          echo "Payload: $payload"
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -d  "${payload}" \
            https://api.github.com/repos/${{ github.repository }}/check-runs
