name: approvals
on: 
  # might be removed later
  pull_request:
    types: [opened]

  pull_request_review:
    types: 
      - submitted
      - edited
      - dismissed

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check Approvals
        id: check-approvals
        run: |
          res=$(python approvals.py approvals_config.yaml)

          state='pending'
        
          if [ "${res}" = '0' ]; then
            state='success'
          fi

          echo "State: $state"
          payload='{
            "context": "approvals",
            "state": "'${state}'",
          }'
          echo "Payload: $payload"
          echo "GH ref: ${{ github.ref }}"
          
          curl -L \
            --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            --data   "${payload}" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.ref }}
