name: approvals
on: 
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check Approvals
        id: check-approvals
        run: |
          find .
          python script.py approvals_config.yaml
        
          if [ $? -ne 0 ]; then
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
              -d '{"title":"test123 check","conclusion":"neutral"}'
              https://api.github.com/repos/${{ github.repository }}/check-runs \

          else 
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
              -d '{"title":"test123 check","conclusion":"success"}'
              https://api.github.com/repos/${{ github.repository }}/check-runs \
          fi
